### ISSUE TITLE
Failure on Windows 10

### ISSUE THREAD

**Issue by sematula** [ijedi1234/Attila2CK2#2]
Hello,

I'm really interested in tacking TWA onto the beginning of a CK2->HOI4 mega-campaign. I tried following the instructions in your readme, and everything seems to work OK until I get to actually running Attila2CK2.exe. It has been a long time since I coded anything, but I pulled up the source in VS and ran a debug. I'm getting:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Attila2CK2
  StackTrace:
   at Attila2CK2.AttilaRegionsInfo.checkIfFactionExists(String factionID) in C:\tmp\Convert\Source\Attila2CK2\AttilaRegionsInfo.cs:line 37
   at Attila2CK2.FactionsInfo.updateFactionsInfo(AttilaRegionsInfo regions) in C:\tmp\Convert\Source\Attila2CK2\FactionsInfo.cs:line 102
   at Attila2CK2.Form1..ctor() in C:\tmp\Convert\Source\Attila2CK2\Form1.cs:line 41
   at Attila2CK2.Program.Main() in C:\tmp\Convert\Source\Attila2CK2\Program.cs:line 16

if I add:

if (!region.getOwningFaction().getID()){
                    return false;
                }

To the checkIfFactionExists() function (method? I forget in C), I get:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Attila2CK2
  StackTrace:
   at Attila2CK2.AttilaRegionsInfo.checkIfFactionExists(String factionID) in C:\tmp\Convert\Source\Attila2CK2\AttilaRegionsInfo.cs:line 32
   at Attila2CK2.FactionsInfo.updateFactionsInfo(AttilaRegionsInfo regions) in C:\tmp\Convert\Source\Attila2CK2\FactionsInfo.cs:line 102
   at Attila2CK2.Form1..ctor() in C:\tmp\Convert\Source\Attila2CK2\Form1.cs:line 41
   at Attila2CK2.Program.Main() in C:\tmp\Convert\Source\Attila2CK2\Program.cs:line 16

Maybe I'm barking up the wrong tree here, but it seems to be dealing with "att_fact_abarshahr" in both cases.

Do I need to have all the DLC installed for this to work? Is there some other in-game config I need to set?

Thanks in advance.

**Comment by sematula** [comment]
Also, this is the file I'm trying to convert.
[Export.zip](https://github.com/ijedi1234/Attila2CK2/files/1730119/Export.zip)

**Comment by sematula** [comment]
Update: I purchased and installed the Empires of Sand DLC, and made a test save. That save converted flawlessly.
